"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { BarChart3, Blocks, Building2, CheckCircle2, CreditCard, LayoutDashboard, LoaderCircle, LogOut, Menu, PackageCheck, RefreshCw, Settings2, SlidersHorizontal, Target, UsersRound, WalletCards, X } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { withBasePath } from "@/lib/site";

type View = "overview" | "leads" | "distribution" | "customers" | "billing" | "catalog" | "plates" | "team" | "settings";
type Account = { id: number; name: string; category: string | null; city: string | null; potential: string; lifecycle_status: string; pipeline_stage: string; follow_up_status: string; owner_member_id: number | null; phone: string | null; email: string | null; client_since: string | null; updated_at: string };
type Member = { id: number; user_id: string; role: string; status: string; capacity: number; name: string };
type Rule = { id: number; name: string; priority: number; strategy: string; active: boolean; assignee_member_id: number | null; conditions: Record<string, unknown> };
type Product = { id: number; name: string; code: string; product_type: string; billing_type: string; interval: string | null; price: number | null; active: boolean };
type Subscription = { id: number; account_id: number; product_id: number; status: string; quantity: number; unit_price: number; billing_interval: string | null };
type Invoice = { id: number; account_id: number; status: string; description: string; amount: number; due_date: string; paid_at: string | null; payment_url: string | null };
type Plate = { id: number; public_id: string; plate_type: string; lifecycle_status: string; account_id: number | null; display_name: string | null; location_label: string | null };
type Tag = { id: number; name: string; color: string; scope: string };
type AccountTag = { account_id: number; tag_id: number };

const nav: Array<{ id: View; label: string; icon: typeof LayoutDashboard }> = [
  { id: "overview", label: "Visão geral", icon: LayoutDashboard }, { id: "leads", label: "Leads", icon: Target },
  { id: "distribution", label: "Distribuição", icon: SlidersHorizontal }, { id: "customers", label: "Clientes", icon: Building2 },
  { id: "billing", label: "Cobrança", icon: WalletCards }, { id: "catalog", label: "Produtos e planos", icon: Blocks },
  { id: "plates", label: "Placas", icon: PackageCheck }, { id: "team", label: "Equipe e acessos", icon: UsersRound },
  { id: "settings", label: "Configurações", icon: Settings2 },
];
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const field = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100";
const stageLabels: Record<string, string> = { new: "Novo", contact_started: "Contato iniciado", diagnostic_presented: "Diagnóstico", proposal_sent: "Proposta", negotiation: "Negociação", won: "Fechado", onboarding: "Implantação", active: "Ativo", renewal: "Renovação", lost: "Perdido" };
const lifecycleLabels: Record<string, string> = { lead: "Lead", onboarding: "Implantação", active: "Ativo", at_risk: "Em risco", delinquent: "Inadimplente", inactive: "Inativo", lost: "Perdido" };

function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</section>; }
function Empty({ children }: { children: ReactNode }) { return <div className="p-10 text-center text-sm text-slate-500">{children}</div>; }
function Title({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: ReactNode }) { return <div className="mb-6 flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-teal-700">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-[-.045em]">{title}</h1><p className="mt-2 text-sm text-slate-500">{detail}</p></div>{action}</div>; }

export default function ManagementLiveWorkspace() {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [view, setView] = useState<View>("overview"); const [menu, setMenu] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [organizationId, setOrganizationId] = useState<number>(); const [organizationName, setOrganizationName] = useState("OctaReview"); const [role, setRole] = useState("");
  const [plateCredential, setPlateCredential] = useState<{ publicId: string; activationCode: string }>();
  const [accounts, setAccounts] = useState<Account[]>([]); const [members, setMembers] = useState<Member[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [products, setProducts] = useState<Product[]>([]); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [plates, setPlates] = useState<Plate[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [accountTags, setAccountTags] = useState<AccountTag[]>([]);
  const canAdmin = role === "admin"; const canFinance = ["admin", "finance"].includes(role);

  const load = useCallback(async () => {
    if (!supabase) return;
    const { data: userData } = await supabase.auth.getUser(); if (!userData.user) return;
    const { data: membership, error: membershipError } = await supabase.from("organization_members").select("organization_id,role").eq("user_id", userData.user.id).eq("status", "active").limit(1).maybeSingle();
    if (membershipError) throw membershipError; if (!membership) throw new Error("Usuário sem organização ativa.");
    setOrganizationId(membership.organization_id); setRole(membership.role);
    const [orgResult, accountResult, memberResult, profileResult, ruleResult, productResult, subscriptionResult, invoiceResult, plateResult, tagResult, accountTagResult] = await Promise.all([
      supabase.from("organizations").select("name").eq("id", membership.organization_id).single(),
      supabase.from("accounts").select("id,name,category,city,potential,lifecycle_status,pipeline_stage,follow_up_status,owner_member_id,phone,email,client_since,updated_at").eq("organization_id", membership.organization_id).order("updated_at", { ascending: false }),
      supabase.from("organization_members").select("id,user_id,role,status,capacity").eq("organization_id", membership.organization_id).order("id"),
      supabase.from("profiles").select("id,full_name,email"),
      supabase.from("distribution_rules").select("id,name,priority,strategy,active,assignee_member_id,conditions").eq("organization_id", membership.organization_id).order("priority"),
      supabase.from("products").select("id,name,code,product_type,billing_type,interval,price,active").eq("organization_id", membership.organization_id).order("name"),
      supabase.from("subscriptions").select("id,account_id,product_id,status,quantity,unit_price,billing_interval").eq("organization_id", membership.organization_id).order("created_at", { ascending: false }),
      supabase.from("invoices").select("id,account_id,status,description,amount,due_date,paid_at,payment_url").eq("organization_id", membership.organization_id).order("due_date", { ascending: false }),
      supabase.from("plates").select("id,public_id,plate_type,lifecycle_status,account_id,display_name,location_label").eq("organization_id", membership.organization_id).order("created_at", { ascending: false }),
      supabase.from("tags").select("id,name,color,scope").eq("organization_id", membership.organization_id).order("name"),
      supabase.from("account_tags").select("account_id,tag_id").eq("organization_id", membership.organization_id),
    ]);
    const firstError = [orgResult, accountResult, memberResult, profileResult, ruleResult, productResult, subscriptionResult, invoiceResult, plateResult, tagResult, accountTagResult].find((result) => result.error)?.error; if (firstError) throw firstError;
    const profileNames = new Map((profileResult.data ?? []).map((profile) => [profile.id, profile.full_name || profile.email || "Usuário"]));
    setOrganizationName(orgResult.data?.name ?? "OctaReview"); setAccounts((accountResult.data ?? []) as Account[]); setMembers((memberResult.data ?? []).map((member) => ({ ...member, name: profileNames.get(member.user_id) ?? "Usuário" })) as Member[]); setRules((ruleResult.data ?? []) as Rule[]); setProducts((productResult.data ?? []) as Product[]); setSubscriptions((subscriptionResult.data ?? []) as Subscription[]); setInvoices((invoiceResult.data ?? []) as Invoice[]); setPlates((plateResult.data ?? []) as Plate[]); setTags((tagResult.data ?? []) as Tag[]); setAccountTags((accountTagResult.data ?? []) as AccountTag[]);
  }, [supabase]);

  useEffect(() => { void (async () => { try { await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar a gestão."); } finally { setLoading(false); } })(); }, [load]);
  async function run(action: () => Promise<void>, message: string) { setBusy(true); setError(undefined); try { await action(); await load(); setNotice(message); window.setTimeout(() => setNotice(undefined), 3000); } catch (caught) { setError(caught instanceof Error ? caught.message : "A operação não foi concluída."); } finally { setBusy(false); } }
  async function signOut() { await supabase?.auth.signOut(); window.location.assign(withBasePath("/login/")); }
  const leads = accounts.filter((account) => account.lifecycle_status === "lead"); const customers = accounts.filter((account) => ["onboarding", "active", "at_risk", "delinquent", "inactive"].includes(account.lifecycle_status));
  const mrr = subscriptions.filter((item) => item.status === "active" && item.billing_interval === "monthly").reduce((sum, item) => sum + Number(item.unit_price) * item.quantity, 0);
  const overdue = invoices.filter((invoice) => invoice.status === "overdue").reduce((sum, invoice) => sum + Number(invoice.amount), 0);
  const memberName = (id: number | null) => members.find((member) => member.id === id)?.name ?? "Não atribuído"; const accountName = (id: number) => accounts.find((account) => account.id === id)?.name ?? `Conta ${id}`;
  const dashboardMetrics: Array<{ label: string; value: string | number; icon: typeof LayoutDashboard }> = [{ label: "Leads", value: leads.length, icon: Target }, { label: "Clientes", value: customers.length, icon: Building2 }, { label: "MRR", value: money.format(mrr), icon: BarChart3 }, { label: "Vencido", value: money.format(overdue), icon: CreditCard }];

  async function createRule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId || !canAdmin) return; const formElement = event.currentTarget; const data = new FormData(formElement); await run(async () => { const assignee = Number(data.get("assignee")) || null; const priority = Number(data.get("priority")); const { error: insertError } = await supabase.from("distribution_rules").insert({ organization_id: organizationId, name: String(data.get("name")), priority, strategy: assignee ? "fixed_member" : "manual", assignee_member_id: assignee, conditions: {} }); if (insertError) throw insertError; formElement.reset(); }, "Regra criada."); }
  async function createProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId || !canAdmin) return; const formElement = event.currentTarget; const data = new FormData(formElement); await run(async () => { const { error: insertError } = await supabase.from("products").insert({ organization_id: organizationId, name: String(data.get("name")), code: String(data.get("code")).trim().toUpperCase(), product_type: String(data.get("type")), billing_type: String(data.get("billing")), interval: data.get("billing") === "recurring" ? String(data.get("interval")) : null, price: Number(data.get("price")) || null, active: true }); if (insertError) throw insertError; formElement.reset(); }, "Produto criado."); }
  async function createInvoice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId || !canFinance) return; const formElement = event.currentTarget; const data = new FormData(formElement); await run(async () => { const { error: insertError } = await supabase.from("invoices").insert({ organization_id: organizationId, account_id: Number(data.get("account")), status: "pending", description: String(data.get("description")), amount: Number(data.get("amount")), due_date: String(data.get("due")), payment_url: String(data.get("url") || "") || null }); if (insertError) throw insertError; formElement.reset(); }, "Cobrança criada."); }
  async function inviteMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId || !canAdmin) return; const formElement = event.currentTarget; const data = new FormData(formElement); await run(async () => { const { data: response, error: functionError } = await supabase.functions.invoke("invite-member", { body: { organizationId, email: String(data.get("email")), fullName: String(data.get("name")), role: String(data.get("role")), accountId: Number(data.get("account")) || undefined } }); if (functionError) throw functionError; if (response?.error) throw new Error(response.error); formElement.reset(); }, "Convite enviado."); }
  async function createSubscription(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId) return; const formElement = event.currentTarget; const data = new FormData(formElement); const product = products.find((item) => item.id === Number(data.get("product"))); if (!product) return; await run(async () => { const { error: insertError } = await supabase.from("subscriptions").insert({ organization_id: organizationId, account_id: Number(data.get("account")), product_id: product.id, status: "active", quantity: Number(data.get("quantity")) || 1, unit_price: Number(data.get("price")) || product.price || 0, billing_interval: product.billing_type === "recurring" ? product.interval || "monthly" : "one_time", due_day: Number(data.get("dueDay")) || null }); if (insertError) throw insertError; formElement.reset(); }, "Serviço vinculado ao cliente."); }
  async function createTag(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId) return; const formElement = event.currentTarget; const data = new FormData(formElement); await run(async () => { const { error: insertError } = await supabase.from("tags").insert({ organization_id: organizationId, name: String(data.get("name")), color: String(data.get("color")), scope: "account" }); if (insertError) throw insertError; formElement.reset(); }, "Tag criada."); }
  async function assignTag(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId) return; const formElement = event.currentTarget; const data = new FormData(formElement); const { data: userData } = await supabase.auth.getUser(); await run(async () => { const { error: insertError } = await supabase.from("account_tags").upsert({ organization_id: organizationId, account_id: Number(data.get("account")), tag_id: Number(data.get("tag")), assigned_by: userData.user?.id }, { onConflict: "account_id,tag_id", ignoreDuplicates: true }); if (insertError) throw insertError; formElement.reset(); }, "Tag aplicada."); }
  async function createPlate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !organizationId || !canAdmin) return; const data = new FormData(event.currentTarget); await run(async () => { const { data: response, error: functionError } = await supabase.functions.invoke("create-plate", { body: { organizationId, plateType: String(data.get("type")) } }); if (functionError) throw functionError; if (response?.error) throw new Error(response.error); setPlateCredential({ publicId: response.plate.publicId, activationCode: response.activationCode }); }, "Placa adicionada ao estoque."); }

  if (!supabase) return <main className="grid min-h-screen place-items-center">Supabase não configurado.</main>;
  return <div className="min-h-screen bg-slate-50 text-slate-950 lg:grid lg:grid-cols-[250px_1fr]">{menu && <button className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden" onClick={() => setMenu(false)} />}
    <aside className={`${menu ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 z-40 flex w-[270px] flex-col border-r border-slate-200 bg-white transition lg:static lg:w-auto lg:translate-x-0`}><div className="flex h-[74px] items-center justify-between border-b border-slate-100 px-5"><Image src={withBasePath("/octareview-wordmark.png")} alt="OctaReview" width={160} height={48} className="h-10 w-auto object-contain" /><button className="lg:hidden" onClick={() => setMenu(false)}><X /></button></div><div className="px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Gestão interna</p><p className="mt-1 truncate text-xs text-slate-500">{organizationName}</p></div><nav className="flex-1 space-y-1 overflow-y-auto px-3">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setView(id); setMenu(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${view === id ? "bg-teal-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon className="size-[18px]" />{label}</button>)}</nav><button onClick={() => void signOut()} className="m-3 flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold text-slate-600"><LogOut className="size-4" />Sair</button></aside>
    <main className="min-w-0"><header className="sticky top-0 z-20 flex h-[68px] items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur lg:px-8"><button className="rounded-xl border p-2 lg:hidden" onClick={() => setMenu(true)}><Menu className="size-5" /></button><div className="flex-1"><p className="text-sm font-bold">{nav.find((item) => item.id === view)?.label}</p><p className="text-[11px] text-slate-400">Perfil: {role || "carregando"}</p></div><button onClick={() => void load()} className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><RefreshCw className="size-4" /></button></header>
      {notice && <div className="fixed right-4 top-20 z-50 flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white"><CheckCircle2 className="size-4" />{notice}</div>}
      <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">{error && <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{loading ? <div className="grid min-h-[60vh] place-items-center"><LoaderCircle className="size-7 animate-spin text-teal-700" /></div> : <>
        {view === "overview" && <><Title eyebrow="Operação real" title="Visão consolidada" detail="Indicadores calculados diretamente da base da organização." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{dashboardMetrics.map(({ label, value, icon: Icon }) => <Card key={label} className="p-5"><Icon className="size-5 text-teal-700" /><strong className="mt-6 block text-3xl">{value}</strong><span className="mt-1 block text-xs text-slate-500">{label}</span></Card>)}</div><Card className="mt-5 overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Atualizações recentes</h2></div>{accounts.length ? accounts.slice(0, 8).map((account) => <div key={account.id} className="flex items-center justify-between border-b border-slate-100 p-4 text-sm"><span><strong>{account.name}</strong><small className="mt-1 block text-slate-500">{stageLabels[account.pipeline_stage] || account.pipeline_stage}</small></span><span className="text-xs text-slate-400">{new Intl.DateTimeFormat("pt-BR").format(new Date(account.updated_at))}</span></div>) : <Empty>Nenhuma empresa cadastrada.</Empty>}</Card></>}
        {view === "leads" && <><Title eyebrow="Comercial" title="Leads" detail="Empresas em prospecção e negociação." /> <AccountTable rows={leads} members={members} busy={busy} onChange={(account, patch) => run(async () => { const { error: updateError } = await supabase.from("accounts").update(patch).eq("id", account.id); if (updateError) throw updateError; }, "Lead atualizado.")} /></>}
        {view === "customers" && <><Title eyebrow="Relacionamento" title="Clientes" detail="Implantação, serviços, tags, risco e inadimplência." /><AccountTable rows={customers} members={members} busy={busy} onChange={(account, patch) => run(async () => { const { error: updateError } = await supabase.from("accounts").update(patch).eq("id", account.id); if (updateError) throw updateError; }, "Cliente atualizado.")} /><div className="mt-5 grid gap-5 xl:grid-cols-3"><Card className="p-5"><h2 className="font-bold">Vincular serviço</h2><form onSubmit={createSubscription} className="mt-4 space-y-3"><select required name="account" className={field}><option value="">Cliente</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required name="product" className={field}><option value="">Produto</option>{products.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input name="quantity" type="number" min="1" defaultValue="1" className={field} /><input name="dueDay" type="number" min="1" max="28" placeholder="Dia" className={field} /></div><input name="price" type="number" min="0" step="0.01" placeholder="Preço negociado" className={field} /><button disabled={busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white">Ativar serviço</button></form></Card><Card className="p-5"><h2 className="font-bold">Criar tag</h2><form onSubmit={createTag} className="mt-4 space-y-3"><input required name="name" placeholder="Nome da tag" className={field} /><input name="color" type="color" defaultValue="#0f766e" className={`${field} p-1`} /><button disabled={busy} className="h-11 w-full rounded-xl border border-teal-200 bg-teal-50 text-sm font-bold text-teal-800">Criar tag</button></form><div className="mt-4 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag.id} className="rounded-full px-3 py-1 text-[10px] font-bold text-white" style={{ backgroundColor: tag.color }}>{tag.name}</span>)}</div></Card><Card className="p-5"><h2 className="font-bold">Aplicar tag</h2><form onSubmit={assignTag} className="mt-4 space-y-3"><select required name="account" className={field}><option value="">Cliente</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required name="tag" className={field}><option value="">Tag</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button disabled={busy} className="h-11 w-full rounded-xl border border-slate-200 text-sm font-bold">Aplicar</button></form><p className="mt-4 text-xs text-slate-500">{accountTags.length} vínculo(s) de tags ativo(s).</p></Card></div></>}
        {view === "distribution" && <><Title eyebrow="Automação comercial" title="Distribuição" detail="Regras reais de responsável por prioridade." /><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-hidden">{rules.length ? rules.map((rule) => <div key={rule.id} className="flex items-center gap-4 border-b border-slate-100 p-5"><div className="grid size-10 place-items-center rounded-xl bg-teal-50 font-bold text-teal-700">{rule.priority}</div><div className="flex-1"><strong className="text-sm">{rule.name}</strong><p className="mt-1 text-xs text-slate-500">{rule.strategy === "fixed_member" ? memberName(rule.assignee_member_id) : "Distribuição manual"}</p></div><button disabled={!canAdmin || busy} onClick={() => run(async () => { const { error: updateError } = await supabase.from("distribution_rules").update({ active: !rule.active }).eq("id", rule.id); if (updateError) throw updateError; }, "Regra atualizada.")} className={`rounded-full px-3 py-1 text-[10px] font-bold ${rule.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{rule.active ? "Ativa" : "Pausada"}</button></div>) : <Empty>Nenhuma regra configurada.</Empty>}</Card><Card className="p-5"><h2 className="font-bold">Nova regra</h2><form onSubmit={createRule} className="mt-5 space-y-3"><input required name="name" placeholder="Nome da regra" className={field} /><input required min={1} name="priority" type="number" placeholder="Prioridade" className={field} /><select name="assignee" className={field}><option value="">Distribuição manual</option>{members.filter((member) => member.status === "active").map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select><button disabled={!canAdmin || busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white disabled:opacity-50">Criar regra</button></form></Card></div></>}
        {view === "billing" && <><Title eyebrow="Financeiro" title="Cobranças" detail="Preparado para receber IDs e links do Asaas quando a API for conectada." /><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Cliente</th><th>Descrição</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t"><td className="p-4 font-semibold">{accountName(invoice.account_id)}</td><td>{invoice.description}</td><td>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${invoice.due_date}T12:00:00`))}</td><td>{money.format(invoice.amount)}</td><td>{invoice.status}</td></tr>)}</tbody></table>{!invoices.length && <Empty>Nenhuma cobrança criada.</Empty>}</Card><Card className="p-5"><h2 className="font-bold">Nova cobrança</h2><form onSubmit={createInvoice} className="mt-5 space-y-3"><select required name="account" className={field}><option value="">Cliente</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required name="description" placeholder="Descrição" className={field} /><input required name="amount" type="number" min="0" step="0.01" placeholder="Valor" className={field} /><input required name="due" type="date" className={field} /><input name="url" type="url" placeholder="Link de pagamento (opcional)" className={field} /><button disabled={!canFinance || busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white disabled:opacity-50">Criar cobrança</button></form></Card></div></>}
        {view === "catalog" && <><Title eyebrow="Oferta" title="Produtos e planos" detail="Catálogo usado nas assinaturas dos clientes." /><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-hidden">{products.length ? products.map((product) => <div key={product.id} className="flex items-center justify-between border-b p-5"><div><strong className="text-sm">{product.name}</strong><p className="mt-1 text-xs text-slate-500">{product.code} · {product.billing_type} · {product.interval || "sem recorrência"}</p></div><strong className="text-sm">{product.price == null ? "Sob proposta" : money.format(product.price)}</strong></div>) : <Empty>Nenhum produto cadastrado.</Empty>}</Card><Card className="p-5"><h2 className="font-bold">Novo produto</h2><form onSubmit={createProduct} className="mt-5 space-y-3"><input required name="name" placeholder="Nome" className={field} /><input required name="code" placeholder="Código" className={field} /><select name="type" className={field}><option value="base_plan">Plano base</option><option value="recurring_addon">Adicional recorrente</option><option value="one_time_project">Projeto</option></select><select name="billing" className={field}><option value="recurring">Recorrente</option><option value="one_time">Único</option><option value="custom">Sob proposta</option></select><select name="interval" className={field}><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="annual">Anual</option></select><input name="price" type="number" min="0" step="0.01" placeholder="Preço" className={field} /><button disabled={!canAdmin || busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white disabled:opacity-50">Criar produto</button></form></Card></div></>}
        {view === "plates" && <><Title eyebrow="Operação física" title="Placas" detail="Estoque, vínculo e status das placas reais." /><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">ID</th><th>Tipo</th><th>Status</th><th>Cliente</th><th>Local</th></tr></thead><tbody>{plates.map((plate) => <tr key={plate.id} className="border-t"><td className="p-4 font-semibold">{plate.public_id}</td><td>{plate.plate_type}</td><td>{plate.lifecycle_status}</td><td>{plate.account_id ? accountName(plate.account_id) : "Disponível"}</td><td>{plate.location_label || plate.display_name || "—"}</td></tr>)}</tbody></table>{!plates.length && <Empty>Nenhuma placa cadastrada no estoque.</Empty>}</Card><Card className="p-5"><h2 className="font-bold">Adicionar ao estoque</h2><form onSubmit={createPlate} className="mt-4 space-y-3"><select name="type" className={field}><option value="main">Placa do estabelecimento</option><option value="employee">Placa de colaborador</option></select><button disabled={!canAdmin || busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white disabled:opacity-50">Gerar placa</button></form>{plateCredential && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-bold text-amber-900">Anote agora — o código não será exibido novamente</p><p className="mt-3 font-mono text-sm">ID: {plateCredential.publicId}</p><p className="mt-1 font-mono text-sm">Código: {plateCredential.activationCode}</p></div>}</Card></div></>}
        {view === "team" && <><Title eyebrow="Acessos" title="Equipe" detail="Usuários e papéis vinculados à organização." /><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><Card className="overflow-hidden">{members.map((member) => <div key={member.id} className="flex items-center gap-4 border-b p-5"><span className="grid size-10 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white">{member.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div className="flex-1"><strong className="text-sm">{member.name}</strong><p className="mt-1 text-xs text-slate-500">{member.role} · capacidade {member.capacity}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase text-emerald-700">{member.status}</span></div>)}</Card><Card className="p-5"><h2 className="font-bold">Convidar usuário</h2><form onSubmit={inviteMember} className="mt-5 space-y-3"><input required name="name" placeholder="Nome" className={field} /><input required name="email" type="email" placeholder="E-mail" className={field} /><select name="role" className={field}><option value="commercial">Comercial</option><option value="success">Sucesso do cliente</option><option value="finance">Financeiro</option><option value="partner">Parceiro</option><option value="customer">Cliente</option><option value="admin">Administrador</option></select><select name="account" className={field}><option value="">Sem estabelecimento específico</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select><button disabled={!canAdmin || busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-bold text-white disabled:opacity-50">Enviar convite</button></form><p className="mt-3 text-[11px] leading-5 text-slate-500">Para perfil Cliente, selecione o estabelecimento que poderá ser acessado.</p></Card></div></>}
        {view === "settings" && <><Title eyebrow="Configuração" title="Organização" detail="Contexto usado em todos os módulos da plataforma." /><Card className="p-6"><dl className="grid gap-5 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Organização</dt><dd className="mt-1 font-bold">{organizationName}</dd></div><div><dt className="text-xs text-slate-500">Seu perfil</dt><dd className="mt-1 font-bold">{role}</dd></div><div><dt className="text-xs text-slate-500">Usuários</dt><dd className="mt-1 font-bold">{members.length}</dd></div><div><dt className="text-xs text-slate-500">Empresas</dt><dd className="mt-1 font-bold">{accounts.length}</dd></div></dl></Card></>}
      </>}</div>
    </main>
  </div>;
}

function AccountTable({ rows, members, busy, onChange }: { rows: Account[]; members: Member[]; busy: boolean; onChange: (account: Account, patch: Record<string, unknown>) => void }) {
  return <Card className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Empresa</th><th>Etapa / status</th><th>Potencial</th><th>Responsável</th><th>Contato</th></tr></thead><tbody>{rows.map((account) => <tr key={account.id} className="border-t"><td className="p-4"><strong>{account.name}</strong><span className="mt-1 block text-xs text-slate-500">{account.category || "Sem categoria"} · {account.city || "Sem cidade"}</span></td><td><select disabled={busy} value={account.lifecycle_status === "lead" ? account.pipeline_stage : account.lifecycle_status} onChange={(event) => { const value = event.target.value; onChange(account, account.lifecycle_status === "lead" ? { pipeline_stage: value, lifecycle_status: value === "won" ? "onboarding" : value === "lost" ? "lost" : "lead", closed_at: value === "won" ? new Date().toISOString() : null } : { lifecycle_status: value }); }} className="h-9 rounded-lg border px-2">{account.lifecycle_status === "lead" ? Object.entries(stageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>) : Object.entries(lifecycleLabels).filter(([value]) => value !== "lead" && value !== "lost").map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td><select disabled={busy} value={account.potential} onChange={(event) => onChange(account, { potential: event.target.value })} className="h-9 rounded-lg border px-2"><option value="high">Alto</option><option value="medium">Médio</option><option value="low">Baixo</option></select></td><td><select disabled={busy} value={account.owner_member_id ?? ""} onChange={(event) => onChange(account, { owner_member_id: Number(event.target.value) || null })} className="h-9 rounded-lg border px-2"><option value="">Não atribuído</option>{members.filter((member) => member.status === "active").map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></td><td><span className="block">{account.phone || "—"}</span><span className="text-xs text-slate-500">{account.email || "—"}</span></td></tr>)}</tbody></table>{!rows.length && <Empty>Nenhum registro nesta área.</Empty>}</Card>;
}
